# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Simon Thordal
description:      'A mathematician and programmer writing about things he is learning about'
url:              http://simonthordal.github.io
baseurl:          /

gems:             [jekyll-paginate, jekyll-gist]
author:
  name:           'Simon Thordal'
  twitter:        https://twitter.com/simonthordal
  github:         https://github.com/simonthordal
  linkedin:       https://es.linkedin.com/in/simon-thordal-6308091

paginate:         5

# Custom vars
version:          2.1.0

analytics :
  provider : google
  google : 
      tracking_id : 'UA-79995324-1'
