# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Simon Thordal
description:      'A blog about things I work on and things that interest me, hopefully with some intersection'
url:              http://simonthordal.github.io
baseurl:          /

gems:             [jekyll-paginate, jekyll-gist, jekyll-sitemap]
author:
  name:           'Simon Thordal'
  twitter:        https://twitter.com/simonthordal
  github:         https://github.com/simonthordal
  linkedin:       https://es.linkedin.com/in/simon-thordal-6308091

paginate:         5

analytics:
  google:
    code:        UA-79995324-1
